/*
 * R-DAS | C# interview task
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: develop@r-das.sk.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using System.Text.Json;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// definition of class DevicesApiController
    /// </summary>
    [ApiController]
    public class DevicesApiController : ControllerBase
    {
        private readonly Parser _parser;
        public DevicesApiController(Parser parser)
        {
            _parser = parser;
        }

        /// <summary>
        /// the method receives from parameter, processes it based on the Parse(body) method, and returns a response
        /// </summary>
        /// <param name="body"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("/service/data")]
        public IActionResult ServiceDataPost(string body)
        {
            try
            {
                return Ok(_parser.Parse(body));
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}
